language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cp googlee736c0dd9c0ecb13.html ./public/googlee736c0dd9c0ecb13.html
  - cd ./public
  - git config --global user.name "waisiukei"
  - git config --global user.email "wakiki@outlook.com"
  - git init
  - git add .
  - git commit -m "Update"
  - git remote add origin https://${GH_TOKEN}@github.com/WaiSiuKei/waisiukei.github.io.git
  - git push --quiet --set-upstream origin master

branches:
  only:
    - master
